name: dependabot-roulette
description:
  Randomly assign dependabot pull requests to members of a GitHub team
author: cmac4603

branding:
  icon: refresh-ccw
  color: red

inputs:
  github_team:
    description: GitHub team to randomly select a user from
    required: true
  github_token:
    description: GitHub token with permissions to read team & members
    required: true

outputs:
  username:
    description: GitHub username of the lucky winner

runs:
  using: node24
  main: dist/index.js
